# Generated by Django 3.0.8 on 2020-07-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200730_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
